import { jsPDF } from "jspdf";
import type { TripPlan } from "../core/utils/tripPlans";
import { extractPlanCities } from "../core/utils/tripPlans";
import type { Country } from "../core/types";

// A4 in points (jsPDF unit: "pt").
const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;
const BOTTOM = PAGE_H - MARGIN;

type RGB = [number, number, number];
const INK: RGB = [30, 41, 59];
const MUTED: RGB = [100, 116, 139];
const ACCENT: RGB = [79, 70, 229];
const RULE: RGB = [226, 232, 240];

const filenameSafe = (s: string): string =>
  s.replace(/[^\w\s-]/g, "").trim().replace(/\s+/g, "-").slice(0, 60) || "itinerary";

/** Suggested download/share filename for a country's itinerary PDF. */
export function itineraryPdfName(country: Country): string {
  return `${filenameSafe(country.name)}-itinerary.pdf`;
}

/**
 * Render a styled, multi-page itinerary PDF and return it as a Blob.
 * jsPDF is bundled into this module's lazy chunk — import it dynamically so it
 * stays out of the initial app bundle.
 */
export function buildItineraryPdfBlob(plan: TripPlan, country: Country, homeCountry: string): Blob {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const cursor = { y: MARGIN };

  const ensureSpace = (needed: number): void => {
    if (cursor.y + needed > BOTTOM) {
      doc.addPage();
      cursor.y = MARGIN;
    }
  };

  const write = (
    text: string,
    opts: { size?: number; color?: RGB; bold?: boolean; gap?: number; indent?: number } = {},
  ): void => {
    const { size = 11, color = INK, bold = false, gap = 4, indent = 0 } = opts;
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, CONTENT_W - indent) as string[];
    const lineHeight = size * 1.35;
    for (const line of lines) {
      ensureSpace(lineHeight);
      doc.text(line, MARGIN + indent, cursor.y);
      cursor.y += lineHeight;
    }
    cursor.y += gap;
  };

  const rule = (): void => {
    ensureSpace(12);
    doc.setDrawColor(RULE[0], RULE[1], RULE[2]);
    doc.setLineWidth(0.75);
    doc.line(MARGIN, cursor.y, PAGE_W - MARGIN, cursor.y);
    cursor.y += 12;
  };

  // Header
  write(country.name, { size: 24, bold: true, gap: 2 });
  const meta = [
    `From ${homeCountry}`,
    country.budget,
    country.bestMonths.length ? `Best months: ${country.bestMonths.join(", ")}` : "",
  ]
    .filter(Boolean)
    .join("  \u00B7  ");
  write(meta, { size: 10, color: MUTED, gap: 10 });

  // Summary line
  const route = extractPlanCities(plan.days);
  const summary = [
    plan.duration,
    `${plan.costPerPerson} / person`,
    route.length ? `${route.length} ${route.length === 1 ? "city" : "cities"}` : "",
  ]
    .filter(Boolean)
    .join("   |   ");
  write(summary, { size: 12, bold: true, gap: route.length ? 6 : 10 });

  if (route.length) {
    write(`Route: ${route.join(" \u2192 ")}`, { size: 10, color: MUTED, gap: 10 });
  }

  if (plan.warning) {
    write(`! ${plan.warning}`, { size: 10, color: [146, 64, 14], gap: 10 });
  }

  rule();

  // Days
  for (const day of plan.days) {
    ensureSpace(40);
    const heading = day.theme ? `${day.label}  —  ${day.theme}` : day.label;
    write(heading, { size: 12, bold: true, color: ACCENT, gap: 4 });
    for (const activity of day.activities) {
      write(`\u2022 ${activity}`, { size: 11, gap: 2, indent: 10 });
    }
    if (day.hotels?.length) {
      write(`Stay: ${day.hotels.join(", ")}`, { size: 10, color: MUTED, gap: 2, indent: 10 });
    }
    cursor.y += 8;
  }

  if (plan.note) {
    rule();
    write(plan.note, { size: 10, color: MUTED, gap: 4 });
  }

  const stamp = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  write(`Generated by Roamwise \u00B7 ${stamp}`, { size: 9, color: MUTED, gap: 0 });

  return doc.output("blob");
}
