/** Centralized localStorage key constants — single source of truth */
export const LS_KEYS = {
  MY_LIST: "tp_my_list",
  CUSTOMS: "tp_customs",
  DELETED: "tp_deleted",
  HOME_COUNTRY: "tp_home_country",
  BUDGET_BASIS: "tp_budget_basis",
  SAVED_TRIPS: "tp_saved_trips",
  FEATURES: "tp_features",
  LLM_KEYS: "tp_llm_keys",
  LLM_PROVIDER: "tp_llm_provider",
  AI_PLANS: "tp_ai_plans",
  LAST_BACKUP: "tp_last_backup",
  BACKUP_FREQUENCY: "tp_backup_frequency",
  BACKUP_SCHEDULE: "tp_backup_schedule",
  BACKUP_TARGET: "tp_backup_target",
  FRE_DONE: "tp_fre_done",
  SCHEMA_VERSION: "tp_schema_version",
  PLAN_DRAFT: "tp_plan_draft",
  PLAN_UI: "tp_plan_ui",
  PLAN_SCOPE: "tp_plan_scope",
  PLAN_REVEAL_SEEN: "tp_plan_reveal_seen",
  LIFECYCLE_DISMISSED: "tp_lifecycle_dismissed",
  LIFECYCLE_BASELINE: "tp_lifecycle_baseline",
} as const;
