/** Centralized localStorage key constants — single source of truth */
export const LS_KEYS = {
  MY_LIST: "tp_my_list",
  VISITED: "tp_visited",
  FAVORITES: "tp_favorites",
  CUSTOMS: "tp_customs",
  DELETED: "tp_deleted",
  HOME_COUNTRY: "tp_home_country",
  BUDGET_BASIS: "tp_budget_basis",
  TRIP_CUSTOMS: "tp_trip_customs",
  TRIP_DELETED: "tp_trip_deleted",
  FEATURES: "tp_features",
  LLM_KEYS: "tp_llm_keys",
  LLM_PROVIDER: "tp_llm_provider",
  AI_PLANS: "tp_ai_plans",
  LAST_BACKUP: "tp_last_backup",
  BACKUP_FREQUENCY: "tp_backup_frequency",
  BACKUP_SCHEDULE: "tp_backup_schedule",
  FRE_DONE: "tp_fre_done",
} as const;
